module.exports={
    releaseStatus:{
        released:"RELEASED",
        coming_soon:"COMING_SOON",
        blocked:"BLOCKED"
    },
    genre:{
        action:"ACTION",
        comedy:"COMEDY",
        drama:"DRAMA",
        fantasy:"FANTASY",
        horror:"HORROR",
        mystery:"MYSTERY",
        romance:"ROMANCE",
        thriller:"THRILLER"
    },
    userType:{
        customer:"CUSTOMER",
        admin:"ADMIN",
        theatre_owner:"THEATRE_OWNER"
    },
    userStatus:{
        pending:"PENDING",
        approved:"APPROVED",
        rejected:"REJECTED"
    }
}